apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackrock-backend-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: blackrock-backend-service
  template:
    metadata:
      labels:
        app: blackrock-backend-service
    spec:
      containers: 
      - name: blackrock-backend-service
        image: {{ .Values.image }}
        ports:
        - containerPort: 3000
        env:
        - name: PAGER_DUTY_API_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: blackrock-backend-configmap
              key: PAGER_DUTY_API_ENDPOINT
        - name: PAGER_DUTY_TOKEN
          valueFrom:
            configMapKeyRef:
              name: blackrock-backend-configmap
              key: PAGER_DUTY_TOKEN
        - name: PAGER_DUTY_USER_EMAIL
          valueFrom:
            configMapKeyRef:
              name: blackrock-backend-configmap
              key: PAGER_DUTY_USER_EMAIL

        - name : SERVICE_NOW_API_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: blackrock-backend-configmap
              key: SERVICE_NOW_API_ENDPOINT
        
        - name : SERVICE_NOW_USERNAME
          valueFrom:
            configMapKeyRef:
              name: blackrock-backend-configmap
              key: SERVICE_NOW_USERNAME
        
        - name : SERVICE_NOW_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: blackrock-backend-configmap
              key: SERVICE_NOW_PASSWORD

        - name: HTTP_PROXY
          valueFrom:
            configMapKeyRef:
              name: blackrock-backend-configmap
              key: HTTP_PROXY

        - name: HTTPS_PROXY
          valueFrom:
            configMapKeyRef:
              name: blackrock-backend-configmap
              key: HTTPS_PROXY
        
        - name: NO_PROXY
          valueFrom:
            configMapKeyRef:
              name: blackrock-backend-configmap
              key: NO_PROXY
        
        