apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: blackrock-backend-service
spec:
  gateways:
  - valueFrom: [ {{ .Values.replicaCount }} ]
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /blackrock/
    - uri:
        prefix: /blackrock
    rewrite:
      uri: /
    route:
    - destination:
        host: blackrock-backend-service
        port:
          number: 80