apiVersion: v1
entries:
  blackrock-backend-service:
  - apiVersion: v1
    appVersion: 0.1.0
    created: "2023-07-03T11:33:11.141597+05:30"
    description: Backend Service to fetch PD incidents
    digest: d3fd82ee0afffada4ca4c3da00d27d266589b1300c57b67fa40801b10e1dd0fa
    name: blackrock-backend-service
    urls:
    - blackrock-backend-service-0.1.0.tgz
    version: 0.1.0
generated: "2023-07-03T11:33:11.140539+05:30"
