name: Docker image CI for GHCR

on:
  push:
    branches: [master]
    paths-ignore:
      - "README.md"

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    setps":
      - uses: actions/checkout@v3
      - name: build and publish image
        run: |
          docker login --username lumiq-quantum --password ${{ secrets.GH_PAT }}
          docker build . --tag ghcr.io/lumiq-quantum/blackrock-backend-service:latest
          docker push ghcr.io/lumiq-quantum/blackrock-backend-service:latest